### ISSUE TITLE
Deformation matrix

### ISSUE THREAD

**Issue by yan99033** [leventt/arap#2]
Hello,

Thanks for sharing the code. I learned a lot from it. About the deformation, I was wondering if there was a bug in your code [here](https://github.com/leventt/arap/blob/b96c04a79be93cd83b5f5d5320ee3c6f37550d1b/inCaseMayaSucks.py#L82).

Since you are applying a transformation to a vertex, shouldn't it be
`deformedVector = deformationMatrices[handleIDs.index(i)].dot(deformedVector)`? Because you are applying a 4x4 transformation matrix to a vertex by doing R * v + t whereas yours is R.T * v.

While I can't validate the code on Maya, I modify the toy example (inCaseMayaSucks.py) to have [inputMatrices](https://github.com/leventt/arap/blob/b96c04a79be93cd83b5f5d5320ee3c6f37550d1b/inCaseMayaSucks.py#L208) set to identity rotation matrix and 0.2 x-translation. Your code does not change the vertex locations while the proposed modification generates a set of vertex locations that makes sense.

**Comment by leventt** [comment]
I just tested modifying the transformation matrix as you suggested:

``` python
print(testAllTheTests(
    # 4 vertex positions (x, y, z)
    [
        [-1., .0, .0],
        [1., .0, .0],
        [.0, .0, -1.],
        [.0, .0, 1.]
    ],
    [[0, 1, 2], [1, 2, 3]],  # triangles from vertex IDs (zero indexed)
    [],  # no fixed verts
    [0],  # first vert is being moved
    # identity matrix isn't very meaningful here I guess, but a good test
    [[
        [1., 0., 0., 0.,],
        [0., 1., 0., 0.,],
        [0., 0., 1., 0.,],
        [0.2, 0., 0., 1.,],
    ]],
    1  # 1 iteration
))
```

and it gives me:

``` python
[[-8.00000000e-01  0.00000000e+00  0.00000000e+00]
 [ 1.20000000e+00  1.77497679e-32  7.40148683e-17]
 [ 2.00000000e-01  2.73638114e-32 -1.00000000e+00]
 [ 2.00000000e-01  2.04616760e-32  1.00000000e+00]]
```

which looks right to me



Perhaps we are using different conventions for transformation matrices?

**Comment by leventt** [comment]
I use row major transformation matrices and perhaps I should have made it more clear but I rarely see code with column major transformation matrices in code bases I interact with. I believe when you have contiguous arrays as in C/C++, it has performance advantages to use row major transformation arrays as it is laid out more conveniently in memory, so it takes advantage of the cpu caches better in most implementations.

here is a good post about it:
https://www.scratchapixel.com/lessons/mathematics-physics-for-computer-graphics/geometry/row-major-vs-column-major-vector

(feel free to open the ticket back if you think it isn't duw to this convention)

**Comment by yan99033** [comment]
Awesome. I was suspecting the same thing. Thanks for the quick reply.

I am so used to the
[R t]
[0 1] 
convention, which is a common way to represent a camera pose in the context of SLAM.
